### ISSUE TITLE
cannot git clone on develop.ontohub.org

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1196]
```
git clone git@develop.ontohub.org:casl-um.git
Klone nach 'casl-um'...
/srv/http/ontohub/current/lib/uri_fetcher/get_caller.rb:2:in `<module:UriFetcher>': uninitialized constant UriFetcher::HTTPCaller (NameError)
	from /srv/http/ontohub/current/lib/uri_fetcher/get_caller.rb:1:in `<top (required)>'
	from /srv/http/ontohub/releases/20150209104606/lib/uri_fetcher.rb:2:in `require'
	from /srv/http/ontohub/releases/20150209104606/lib/uri_fetcher.rb:2:in `<module:UriFetcher>'
	from /srv/http/ontohub/releases/20150209104606/lib/uri_fetcher.rb:1:in `<top (required)>'
	from /srv/http/ontohub/current/git/lib/ontohub_net.rb:5:in `require'
	from /srv/http/ontohub/current/git/lib/ontohub_net.rb:5:in `<top (required)>'
	from /srv/http/ontohub/current/git/lib/init.rb:18:in `require'
	from /srv/http/ontohub/current/git/lib/init.rb:18:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /srv/http/ontohub/current/git/bin/git-shell:11:in `<main>'
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by tillmo** [comment]
works now
