### ISSUE TITLE
undefined method 'underscore';  null value in column "display_name" violates not-null constraint

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1348]
During review of #1326, when I try a proof, I get `undefined method 'underscore' for nil:NilClass`:
```
2015-05-17T14:47:39.858Z 9151 TID-1hwq6s CollectiveProofAttemptWorker JID-eb635b32eee65c5c398acd40 INFO: start
2015-05-17T14:47:40.637Z 9151 TID-1hwq6s CollectiveProofAttemptWorker JID-eb635b32eee65c5c398acd40 DEBUG: Failure! Retry 0 in 33 seconds
2015-05-17T14:47:40.638Z 9151 TID-1hwq6s CollectiveProofAttemptWorker JID-eb635b32eee65c5c398acd40 INFO: fail: 0.78 sec
2015-05-17T14:47:40.639Z 9151 TID-1hwq6s WARN: {"retry"=>true, "queue"=>"hets", "class"=>"CollectiveProofAttemptWorker", "args"=>["OntologyVersion", 5, {"{\"options\":{\"prover\":\"darwin\"}}"=>[6]}], "jid"=>"eb635b32eee65c5c398acd40", "enqueued_at"=>1431874059.8539615, "error_message"=>"undefined method `underscore' for nil:NilClass", "error_class"=>"NoMethodError", "failed_at"=>1431874060.6378937, "retry_count"=>0, "processor"=>"mark:9151"}
2015-05-17T14:47:40.639Z 9151 TID-1hwq6s WARN: undefined method `underscore' for nil:NilClass
2015-05-17T14:47:40.639Z 9151 TID-1hwq6s WARN: /home/till/web2.0/ontohub/lib/hets/prove/prove_evaluator.rb:121:in `goal_info'
/home/till/web2.0/ontohub/lib/hets/prove/prove_evaluator.rb:101:in `proof_attempt_info'
/home/till/web2.0/ontohub/lib/hets/prove/prove_evaluator.rb:57:in `add_array_value'
/home/till/web2.0/ontohub/lib/hets/base_evaluator.rb:54:in `block in process'
/home/till/web2.0/ontohub/lib/hets/base_evaluator.rb:53:in `each'
/home/till/web2.0/ontohub/lib/hets/base_evaluator.rb:53:in `process'
/home/till/web2.0/ontohub/lib/hets/json_parser.rb:37:in `call_back'
/home/till/web2.0/ontohub/lib/hets/prove/parser.rb:25:in `process_value'
/home/till/web2.0/ontohub/lib/hets/json_parser.rb:95:in `value'
/home/till/web2.0/ontohub/lib/hets/json_parser.rb:33:in `block in initialize_parser_hooks'
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/json-stream-0.2.1/lib/json/stream/parser.rb:452:in `call'
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/json-stream-0.2.1/lib/json/stream/parser.rb:452:in `block in notify'
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/json-stream-0.2.1/lib/json/stream/parser.rb:451:in `each'
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/json-stream-0.2.1/lib/json/stream/parser.rb:451:in `notify'
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/json-stream-0.2.1/lib/json/stream/parser.rb:574:in `end_value'
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/json-stream-0.2.1/lib/json/stream/parser.rb:178:in `block in <<'
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/json-stream-0.2.1/lib/json/stream/parser.rb:157:in `each_char'
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/json-stream-0.2.1/lib/json/stream/parser.rb:157:in `<<'
/home/till/web2.0/ontohub/lib/hets/json_parser.rb:17:in `parse'
/home/till/web2.0/ontohub/lib/hets/prove/importer.rb:31:in `block in import'
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
/home/till/web2.0/ontohub/lib/hets/prove/importer.rb:29:in `import'
/home/till/web2.0/ontohub/app/models/ontology/import.rb:20:in `import_proof'
/home/till/web2.0/ontohub/lib/collective_proof_attempt.rb:64:in `prove'
/home/till/web2.0/ontohub/lib/collective_proof_attempt.rb:55:in `block in run_body'
/home/till/web2.0/ontohub/lib/collective_proof_attempt.rb:53:in `each'
/home/till/web2.0/ontohub/lib/collective_proof_attempt.rb:53:in `run_body'
/home/till/web2.0/ontohub/lib/collective_proof_attempt.rb:22:in `block in run'
/home/till/web2.0/ontohub/lib/state_updater.rb:20:in `do_or_set_failed'
/home/till/web2.0/ontohub/lib/collective_proof_attempt.rb:12:in `run'
/home/till/web2.0/ontohub/lib/collective_proof_attempt_worker.rb:22:in `perform'
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/sidekiq-3.2.4/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
```
On staging, I get a different error (`undefined method 'proof_attempts' for nil:NilClass`) which is probably due to the my database.

Since I thought that this might be in general a problem of my database, I did `rake db:migrate:clean` and `rake db:seed` and get
```
In »»/home/till/web2.0/ontohub/spec/fixtures/ontologies/proof_statuses.owl«« speichern.

    [ <=>                                                                                         ] 57.527      --.-K/s   in 0,1s    

2015-05-17 16:55:48 (431 KB/s) - »/home/till/web2.0/ontohub/spec/fixtures/ontologies/proof_statuses.owl« gespeichert [57527]

rake aborted!
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "display_name" violates not-null constraint
DETAIL:  Failing row contains (1, QuickCheck, 2015-05-17 14:55:57.25343, 2015-05-17 14:55:57.25343, null).
: INSERT INTO "provers" ("created_at", "display_name", "name", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'
```
The same problem already occurs on staging.

**Comment by eugenk** [comment]
This is probably because #1343 is not yet merged and you are on a hets revision greater than or equal to 1430921534.

**Comment by tillmo** [comment]
indeed, after the merge of #1343, this problem has vanished.
