### ISSUE TITLE
staging tests failing on at least one development machine

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#1358]
Something seems to be wrong in ontohub-land. At least on my machine, the tests consistently fail.
We started from #1255, the issues persist for me on staging - which actually makes sense, as the gem-updates shouldn't produce these problems.

Let's start from the beginning:

- Given i have "staging" checked out
- And i run `git clean -fdX spec/`
- And i run `script/rebuild-ontohub`
- When i run `bundle exec rake`

This error occurs:
```
Calling hets/provers on "spec/fixtures/ontologies/rdf/sample.rdf"
Calling hets/prove on "spec/fixtures/ontologies/prove/Simple_Implications.casl"
Calling hets/prove on "spec/fixtures/ontologies/prove/Simple_Implications.casl"
Calling hets/prove on "spec/fixtures/ontologies/prove/Simple_Implications.casl"
Calling hets/prove on "spec/fixtures/ontologies/prove/Simple_Implications.casl"
Calling hets/prove on "spec/fixtures/ontologies/prove/Simple_Implications.casl"
rake aborted!
JSON::ParserError: 757: unexpected token at '*** Error: no matching translation or prover found
'
/usr/local/var/rbenv/versions/2.1/gemsets/global/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
/usr/local/var/rbenv/versions/2.1/gemsets/global/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/prover_output_generator.rb:17:in `block (2 levels) in perform'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/prover_output_generator.rb:13:in `each'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/prover_output_generator.rb:13:in `block in perform'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/prover_output_generator.rb:12:in `each'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/prover_output_generator.rb:12:in `perform'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/base_generator.rb:21:in `block in call'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/base_generator.rb:109:in `call'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/base_generator.rb:109:in `block in on_outdated_cassettes'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/base_generator.rb:108:in `each'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/base_generator.rb:108:in `on_outdated_cassettes'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/base_generator.rb:20:in `call'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/direct_hets_generator.rb:10:in `block in call'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/base_generator.rb:74:in `call'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/base_generator.rb:74:in `with_running'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/base_generator.rb:33:in `with_running_hets'
/Users/robustus/uni/ontospace/ontohub/spec/support/fixtures_generation/direct_hets_generator.rb:10:in `call'
/Users/robustus/uni/ontospace/ontohub/lib/tasks/test.rake:22:in `each'
/Users/robustus/uni/ontospace/ontohub/lib/tasks/test.rake:22:in `block (2 levels) in <top (required)>'
Tasks: TOP => default => test:freshen_fixtures
(See full trace by running task with --trace)
```

- When i run `bundle exec rake` again

This error usually/pretty much always occurs:
```
Failures:

  1) Hets::Prove::SZSParser darwin-non-fd on CounterSatisfiable returns status 'CounterSatisfiable'
     Failure/Error: expect(Hets::Prove::SZSParser.new(prover, output).call).

       expected: "CounterSatisfiable"
            got: nil

       (compared using ==)
     # ./spec/lib/hets/szs_parser_spec.rb:22:in `block (5 levels) in <top (required)>'

  2) Hets::Prove::SZSParser darwin on CounterSatisfiable returns status 'CounterSatisfiable'
     Failure/Error: expect(Hets::Prove::SZSParser.new(prover, output).call).

       expected: "CounterSatisfiable"
            got: nil

       (compared using ==)
     # ./spec/lib/hets/szs_parser_spec.rb:22:in `block (5 levels) in <top (required)>'

Finished in 10 minutes 23 seconds
1614 examples, 2 failures, 3 pending

Failed examples:

rspec ./spec/lib/hets/szs_parser_spec.rb:21 # Hets::Prove::SZSParser darwin-non-fd on CounterSatisfiable returns status 'CounterSatisfiable'
rspec ./spec/lib/hets/szs_parser_spec.rb:21 # Hets::Prove::SZSParser darwin on CounterSatisfiable returns status 'CounterSatisfiable'
```

On other times (but hard to effectively reproduce), the bootup of the rails-server 3001 will occur in foreground (at least it looks like that) and the tests seem to stall.

**Comment by eugenk** [comment]
Thanks, this gives me some important information, that I didn't have in #1255.

It seems like there is a problem with the darwin and darwin-non-fd provers. I almost don't dare to ask: Do you have darwin installed?

```
❯ darwin -v
Darwin 1.4.4
```


> On other times (but hard to effectively reproduce), the bootup of the rails-server 3001 will occur in foreground (at least it looks like that) and the tests seem to stall.

This should not happen. The rails server starts on port 3001 to generate VCR cassettes for proofs with specific options. Those cassettes are in the git repository, though.

**Comment by eugenk** [comment]
Followup question on darwin: What do
```bash
curl -X POST -H "Content-Type: application/json" -d '{"format":"json", "prover":"darwin"}' http://localhost:8000/prove/file%3A%2F%2F%2Fescaped%2Fpath%2Fto%2Fontohub%2Fspec%2Ffixtures%2Fontologies%2Fprove%2FSimple_Implications.casl/auto
```
and
```bash
curl -X POST -H "Content-Type: application/json" -d '{"format":"json", "prover":"darwin-non-fd"}' http://localhost:8000/prove/file%3A%2F%2F%2Fescaped%2Fpath%2Fto%2Fontohub%2Fspec%2Ffixtures%2Fontologies%2Fprove%2FSimple_Implications.casl/auto
```
print?

**Comment by 0robustus1** [comment]
Darwin is present. It also yields the same version as yours (which makes sense, considering i added the package to our homebrew-tap ;) ).

With regard to the rails server: I thought the same thing. And what is especially confounding is the fact that you start it by forking the process, so it shouldn't really have control. I will try to come up with something reproducible. Also @ebolloff doesn't seem to have this issue, so we should disregard the rails-3001-issue for now.

**Comment by 0robustus1** [comment]
```
curl -X POST -H "Content-Type: application/json" -d '{"format":"json", "prover":"darwin"}' http://localhost:8000/prove/file%3A%2F%2F%2Fescaped%2Fpath%2Fto%2Fontohub%2Fspec%2Ffixtures%2Fontologies%2Fprove%2FSimple_Implications.casl/auto
```

```json
[{
"node": "CounterSatisfiable",
"goals": [{
 "name": "Ax2",
 "result": "Open\n",
 "details": "",
 "used_prover": { "identifier": "darwin", "name": "darwin" },
 "used_translation": "CASL2SoftFOL",
 "tactic_script": { "time_limit": 1, "extra_options": [] },
 "proof_tree": "",
 "used_time": {
  "seconds": -1,
  "components": { "hours": -1, "mins": 59, "secs": 59 }
  },
 "used_axioms": [],
 "prover_output":
  "Darwin 1.4.4\n\nFinite Domain: setting initial domain size to 1.\nFinite Domain: using non-ground splitting in preprocessing.\n\nParsing /var/folders/w0/l8p5_vf14f1b9bj1yzs9hydw0000gn/T/_ax25570.tptp ...\n\nCouldn't find eprover, need version 0.91 or higher to clausify input.\nSpecify path to eprover with flag '--eprover'.\nSZS status GaveUp(FOF)\n"
 }]
}, {
"node": "Theorem",
"goals": [{
 "name": "Ax1",
 "result": "Open\n",
 "details": "",
 "used_prover": { "identifier": "darwin", "name": "darwin" },
 "used_translation": "CASL2SoftFOL",
 "tactic_script": { "time_limit": 1, "extra_options": [] },
 "proof_tree": "",
 "used_time": {
  "seconds": -1,
  "components": { "hours": -1, "mins": 59, "secs": 59 }
  },
 "used_axioms": [],
 "prover_output":
  "Darwin 1.4.4\n\nFinite Domain: setting initial domain size to 1.\nFinite Domain: using non-ground splitting in preprocessing.\n\nParsing /var/folders/w0/l8p5_vf14f1b9bj1yzs9hydw0000gn/T/_ax15570.tptp ...\n\nCouldn't find eprover, need version 0.91 or higher to clausify input.\nSpecify path to eprover with flag '--eprover'.\nSZS status GaveUp(FOF)\n"
 }]
}, {
"node": "Group",
"goals": [{
 "name": "rightunit",
 "result": "Open\n",
 "details": "",
 "used_prover": { "identifier": "darwin", "name": "darwin" },
 "used_translation": "CASL2SoftFOL",
 "tactic_script": { "time_limit": 1, "extra_options": [] },
 "proof_tree": "",
 "used_time": {
  "seconds": -1,
  "components": { "hours": -1, "mins": 59, "secs": 59 }
  },
 "used_axioms": [],
 "prover_output":
  "Darwin 1.4.4\n\nFinite Domain: setting initial domain size to 1.\nFinite Domain: using non-ground splitting in preprocessing.\n\nParsing /var/folders/w0/l8p5_vf14f1b9bj1yzs9hydw0000gn/T/_rightunit5570.tptp ...\n\nCouldn't find eprover, need version 0.91 or higher to clausify input.\nSpecify path to eprover with flag '--eprover'.\nSZS status GaveUp(FOF)\n"
 }]
}]
```

```
curl -X POST -H "Content-Type: application/json" -d '{"format":"json", "prover":"darwin-non-fd"}' http://localhost:8000/prove/file%3A%2F%2F%2Fescaped%2Fpath%2Fto%2Fontohub%2Fspec%2Ffixtures%2Fontologies%2Fprove%2FSimple_Implications.casl/auto
```

```json
[{
"node": "CounterSatisfiable",
"goals": [{
 "name": "Ax2",
 "result": "Open\n",
 "details": "",
 "used_prover": {
  "identifier": "darwin-non-fd", "name": "darwin-non-fd" },
 "used_translation": "CASL2SoftFOL",
 "tactic_script": { "time_limit": 1, "extra_options": [] },
 "proof_tree": "",
 "used_time": {
  "seconds": -1,
  "components": { "hours": -1, "mins": 59, "secs": 59 }
  },
 "used_axioms": [],
 "prover_output":
  "Darwin 1.4.4\n\n\nParsing /var/folders/w0/l8p5_vf14f1b9bj1yzs9hydw0000gn/T/_ax25570.tptp ...\n\nCouldn't find eprover, need version 0.91 or higher to clausify input.\nSpecify path to eprover with flag '--eprover'.\nSZS status GaveUp(FOF)\n"
 }]
}, {
"node": "Theorem",
"goals": [{
 "name": "Ax1",
 "result": "Open\n",
 "details": "",
 "used_prover": {
  "identifier": "darwin-non-fd", "name": "darwin-non-fd" },
 "used_translation": "CASL2SoftFOL",
 "tactic_script": { "time_limit": 1, "extra_options": [] },
 "proof_tree": "",
 "used_time": {
  "seconds": -1,
  "components": { "hours": -1, "mins": 59, "secs": 59 }
  },
 "used_axioms": [],
 "prover_output":
  "Darwin 1.4.4\n\n\nParsing /var/folders/w0/l8p5_vf14f1b9bj1yzs9hydw0000gn/T/_ax15570.tptp ...\n\nCouldn't find eprover, need version 0.91 or higher to clausify input.\nSpecify path to eprover with flag '--eprover'.\nSZS status GaveUp(FOF)\n"
 }]
}, {
"node": "Group",
"goals": [{
 "name": "rightunit",
 "result": "Open\n",
 "details": "",
 "used_prover": {
  "identifier": "darwin-non-fd", "name": "darwin-non-fd" },
 "used_translation": "CASL2SoftFOL",
 "tactic_script": { "time_limit": 1, "extra_options": [] },
 "proof_tree": "",
 "used_time": {
  "seconds": -1,
  "components": { "hours": -1, "mins": 59, "secs": 59 }
  },
 "used_axioms": [],
 "prover_output":
  "Darwin 1.4.4\n\n\nParsing /var/folders/w0/l8p5_vf14f1b9bj1yzs9hydw0000gn/T/_rightunit5570.tptp ...\n\nCouldn't find eprover, need version 0.91 or higher to clausify input.\nSpecify path to eprover with flag '--eprover'.\nSZS status GaveUp(FOF)\n"
 }]
}]
```

**Comment by eugenk** [comment]
Very weird. Your output differs from mine. For example, my goals have either the result `"Proved"` or `"Disproved"` instead of `"Open\n"`. However, this should not lead to the `JSON::ParserError` [reported in #1255](https://github.com/ontohub/ontohub/pull/1255#issuecomment-106274530).

The following provers are used in the generator: `SPASS`, `darwin`, darwin-non-fd`, `eprover`
Can you please try the same curl command with the remaining two provers?

**Comment by 0robustus1** [comment]
- SPASS

```json
[{
"node": "CounterSatisfiable",
"goals": [{
 "name": "Ax2",
 "result": "Disproved",
 "details": "",
 "used_prover": { "identifier": "SPASS", "name": "SPASS" },
 "used_translation": "CASL2SoftFOL",
 "tactic_script": {
  "time_limit": 1, "extra_options": [ "-DocProof"] },
 "proof_tree": "",
 "used_time": {
  "seconds": 0, "components": { "hours": 0, "mins": 0, "secs": 0 }
  },
 "used_axioms": [],
 "prover_output":
  "\n--------------------------SPASS-START-----------------------------\nInput Problem:\n1[0:Inp] ||  -> equal(zero,one)**.\n2[0:Inp] ||  -> equal(U,zero)*.\n This is a unit equality problem.\n This is a problem that has, if any, a finite domain model.\n There is a finite domain clause.\n There are no function symbols.\n The conjecture is ground.\n Axiom clauses: 1 Conjecture clauses: 1\n Inferences: ISpR=1 ISpL=1 \n Reductions: RFRew=1 RBRew=1 RFMRR=1 RBMRR=1 RObv=1 RUnC=1 RTaut=1 RFSub=1 RBSub=1 \n Extras    : Input Saturation, Always Selection, No Splitting, Full Reduction,  Ratio: 5, FuncWeight: 1, VarWeight: 1\n Precedence: zero > one\n Ordering  : KBO\nProcessed Problem:\n\nWorked Off Clauses:\n\nUsable Clauses:\n3[0:Rew:1.0,2.0] ||  -> equal(U,one)*.\n\tGiven clause: 3[0:Rew:1.0,2.0] ||  -> equal(U,one)*.\n\tGiven clause: 5[0:SpR:3.0,3.0] ||  -> equal(U,V)*.\nSPASS V 3.7 \nSPASS beiseite: Completion found.\nProblem: Read from stdin. \nSPASS derived 3 clauses, backtracked 0 clauses, performed 0 splits and kept 4 clauses.\nSPASS allocated 45932 KBytes.\nSPASS spent\t0:00:00.04 on the problem.\n\t\t0:00:00.02 for the input.\n\t\t0:00:00.01 for the FLOTTER CNF translation.\n\t\t0:00:00.00 for inferences.\n\t\t0:00:00.00 for the backtracking.\n\t\t0:00:00.00 for the reduction.\n\n\n The saturated set of worked-off clauses is :\n5[0:SpR:3.0,3.0] ||  -> equal(U,V)*.\n--------------------------SPASS-STOP------------------------------\n"
 }]
}, {
"node": "Theorem",
"goals": [{
 "name": "Ax1",
 "result": "Proved",
 "details": "",
 "used_prover": { "identifier": "SPASS", "name": "SPASS" },
 "used_translation": "CASL2SoftFOL",
 "tactic_script": {
  "time_limit": 1, "extra_options": [ "-DocProof"] },
 "proof_tree": "",
 "used_time": {
  "seconds": 0, "components": { "hours": 0, "mins": 0, "secs": 0 }
  },
 "used_axioms": [],
 "prover_output":
  "\n--------------------------SPASS-START-----------------------------\nInput Problem:\n1[0:Inp] || equal(skc1,skc1)* -> .\n This is a unit equality problem.\n This is a problem that has, if any, a finite domain model.\n There are no function symbols.\n The conjecture is ground.\n Axiom clauses: 0 Conjecture clauses: 1\n Inferences: IEqR=1 \n Reductions: RFMRR=1 RBMRR=1 RObv=1 RUnC=1 RTaut=1 RFSub=1 RBSub=1 \n Extras    : Input Saturation, Always Selection, No Splitting, Full Reduction,  Ratio: 5, FuncWeight: 1, VarWeight: 1\n Precedence: zero > skc0 > skc1\n Ordering  : KBO\nProcessed Problem:\n\nWorked Off Clauses:\n\nUsable Clauses:\n\nSPASS V 3.7 \nSPASS beiseite: Proof found.\nProblem: Read from stdin. \nSPASS derived 0 clauses, backtracked 0 clauses, performed 0 splits and kept 1 clauses.\nSPASS allocated 45930 KBytes.\nSPASS spent\t0:00:00.03 on the problem.\n\t\t0:00:00.01 for the input.\n\t\t0:00:00.01 for the FLOTTER CNF translation.\n\t\t0:00:00.00 for inferences.\n\t\t0:00:00.00 for the backtracking.\n\t\t0:00:00.00 for the reduction.\n\n\nHere is a proof with depth 0, length 2 :\n1[0:Inp] || equal(skc1,skc1)* -> .\n2[0:Obv:1.0] ||  -> .\nFormulae used in the proof : ax1\n\n--------------------------SPASS-STOP------------------------------\n"
 }]
}, {
"node": "Group",
"goals": [{
 "name": "rightunit",
 "result": "Proved",
 "details": "",
 "used_prover": { "identifier": "SPASS", "name": "SPASS" },
 "used_translation": "CASL2SoftFOL",
 "tactic_script": {
  "time_limit": 1, "extra_options": [ "-DocProof"] },
 "proof_tree": "",
 "used_time": {
  "seconds": 0, "components": { "hours": 0, "mins": 0, "secs": 0 }
  },
 "used_axioms": [ "leftunit", "Ax2", "ga_assoc___+__"],
 "prover_output":
  "\n--------------------------SPASS-START-----------------------------\nInput Problem:\n1[0:Inp] ||  -> equal(o__Plus__(U,zero),U)**.\n2[0:Inp] || equal(o__Plus__(zero,skc1),skc1)** -> .\n3[0:Inp] ||  -> equal(o__Plus__(U,minus__(U)),zero)**.\n4[0:Inp] ||  -> equal(o__Plus__(o__Plus__(U,V),W),o__Plus__(U,o__Plus__(V,W)))**.\n This is a unit equality problem.\n This is a problem that has, if any, a non-trivial domain model.\n The conjecture is ground.\n Axiom clauses: 3 Conjecture clauses: 1\n Inferences: IEqR=1 ISpR=1 ISpL=1 \n Reductions: RFRew=1 RBRew=1 RFMRR=1 RBMRR=1 RObv=1 RUnC=1 RTaut=1 RFSub=1 RBSub=1 \n Extras    : Input Saturation, No Selection, No Splitting, Full Reduction,  Ratio: 5, FuncWeight: 1, VarWeight: 1\n Precedence: o__Plus__ > minus__ > skc1 > skc0 > zero\n Ordering  : KBO\nProcessed Problem:\n\nWorked Off Clauses:\n\nUsable Clauses:\n1[0:Inp] ||  -> equal(o__Plus__(U,zero),U)**.\n2[0:Inp] || equal(o__Plus__(zero,skc1),skc1)** -> .\n3[0:Inp] ||  -> equal(o__Plus__(U,minus__(U)),zero)**.\n4[0:Inp] ||  -> equal(o__Plus__(o__Plus__(U,V),W),o__Plus__(U,o__Plus__(V,W)))**.\n\tGiven clause: 1[0:Inp] ||  -> equal(o__Plus__(U,zero),U)**.\n\tGiven clause: 2[0:Inp] || equal(o__Plus__(zero,skc1),skc1)** -> .\n\tGiven clause: 3[0:Inp] ||  -> equal(o__Plus__(U,minus__(U)),zero)**.\n\tGiven clause: 4[0:Inp] ||  -> equal(o__Plus__(o__Plus__(U,V),W),o__Plus__(U,o__Plus__(V,W)))**.\n\tGiven clause: 11[0:SpR:1.0,4.0] ||  -> equal(o__Plus__(U,o__Plus__(zero,V)),o__Plus__(U,V))**.\n\tGiven clause: 21[0:Rew:1.0,20.0] ||  -> equal(o__Plus__(U,minus__(zero)),U)**.\n\tGiven clause: 8[0:SpR:4.0,3.0] ||  -> equal(o__Plus__(U,o__Plus__(V,minus__(o__Plus__(U,V)))),zero)**.\n\tGiven clause: 12[0:SpR:3.0,4.0] ||  -> equal(o__Plus__(U,o__Plus__(minus__(U),V)),o__Plus__(zero,V))**.\n\tGiven clause: 67[0:Rew:1.0,61.0] ||  -> equal(o__Plus__(zero,minus__(minus__(U))),U)**.\nSPASS V 3.7 \nSPASS beiseite: Proof found.\nProblem: Read from stdin. \nSPASS derived 48 clauses, backtracked 0 clauses, performed 0 splits and kept 17 clauses.\nSPASS allocated 46026 KBytes.\nSPASS spent\t0:00:00.05 on the problem.\n\t\t0:00:00.01 for the input.\n\t\t0:00:00.02 for the FLOTTER CNF translation.\n\t\t0:00:00.00 for inferences.\n\t\t0:00:00.00 for the backtracking.\n\t\t0:00:00.00 for the reduction.\n\n\nHere is a proof with depth 3, length 11 :\n1[0:Inp] ||  -> equal(o__Plus__(U,zero),U)**.\n2[0:Inp] || equal(o__Plus__(zero,skc1),skc1)** -> .\n3[0:Inp] ||  -> equal(o__Plus__(U,minus__(U)),zero)**.\n4[0:Inp] ||  -> equal(o__Plus__(o__Plus__(U,V),W),o__Plus__(U,o__Plus__(V,W)))**.\n11[0:SpR:1.0,4.0] ||  -> equal(o__Plus__(U,o__Plus__(zero,V)),o__Plus__(U,V))**.\n12[0:SpR:3.0,4.0] ||  -> equal(o__Plus__(U,o__Plus__(minus__(U),V)),o__Plus__(zero,V))**.\n61[0:SpR:3.0,12.0] ||  -> equal(o__Plus__(zero,minus__(minus__(U))),o__Plus__(U,zero))**.\n67[0:Rew:1.0,61.0] ||  -> equal(o__Plus__(zero,minus__(minus__(U))),U)**.\n77[0:SpR:67.0,11.0] ||  -> equal(o__Plus__(U,minus__(minus__(V))),o__Plus__(U,V))**.\n79[0:Rew:77.0,67.0] ||  -> equal(o__Plus__(zero,U),U)**.\n80[0:UnC:79.0,2.0] ||  -> .\nFormulae used in the proof : leftunit rightunit ax2 ga_assoc___Plus__\n\n--------------------------SPASS-STOP------------------------------\n"
 }, {
 "name": "zero_plus",
 "result": "Proved",
 "details": "",
 "used_prover": { "identifier": "SPASS", "name": "SPASS" },
 "used_translation": "CASL2SoftFOL",
 "tactic_script": {
  "time_limit": 1, "extra_options": [ "-DocProof"] },
 "proof_tree": "",
 "used_time": {
  "seconds": 0, "components": { "hours": 0, "mins": 0, "secs": 0 }
  },
 "used_axioms": [ "rightunit"],
 "prover_output":
  "\n--------------------------SPASS-START-----------------------------\nInput Problem:\n1[0:Inp] ||  -> equal(o__Plus__(zero,U),U)**.\n2[0:Inp] ||  -> equal(o__Plus__(U,zero),U)**.\n3[0:Inp] || equal(o__Plus__(zero,zero),zero)** -> .\n4[0:Inp] ||  -> equal(o__Plus__(U,minus__(U)),zero)**.\n5[0:Inp] ||  -> equal(o__Plus__(o__Plus__(U,V),W),o__Plus__(U,o__Plus__(V,W)))**.\n This is a unit equality problem.\n This is a problem that has, if any, a non-trivial domain model.\n The conjecture is ground.\n Axiom clauses: 4 Conjecture clauses: 1\n Inferences: IEqR=1 ISpR=1 ISpL=1 \n Reductions: RFRew=1 RBRew=1 RFMRR=1 RBMRR=1 RObv=1 RUnC=1 RTaut=1 RFSub=1 RBSub=1 \n Extras    : Input Saturation, No Selection, No Splitting, Full Reduction,  Ratio: 5, FuncWeight: 1, VarWeight: 1\n Precedence: o__Plus__ > minus__ > zero\n Ordering  : KBO\nProcessed Problem:\n\nWorked Off Clauses:\n\nUsable Clauses:\n1[0:Inp] ||  -> equal(o__Plus__(zero,U),U)**.\n2[0:Inp] ||  -> equal(o__Plus__(U,zero),U)**.\n4[0:Inp] ||  -> equal(o__Plus__(U,minus__(U)),zero)**.\n5[0:Inp] ||  -> equal(o__Plus__(o__Plus__(U,V),W),o__Plus__(U,o__Plus__(V,W)))**.\nSPASS V 3.7 \nSPASS beiseite: Proof found.\nProblem: Read from stdin. \nSPASS derived 0 clauses, backtracked 0 clauses, performed 0 splits and kept 4 clauses.\nSPASS allocated 45941 KBytes.\nSPASS spent\t0:00:00.03 on the problem.\n\t\t0:00:00.01 for the input.\n\t\t0:00:00.01 for the FLOTTER CNF translation.\n\t\t0:00:00.00 for inferences.\n\t\t0:00:00.00 for the backtracking.\n\t\t0:00:00.00 for the reduction.\n\n\nHere is a proof with depth 0, length 4 :\n1[0:Inp] ||  -> equal(o__Plus__(zero,U),U)**.\n3[0:Inp] || equal(o__Plus__(zero,zero),zero)** -> .\n6[0:Rew:1.0,3.0] || equal(zero,zero)* -> .\n7[0:Obv:6.0] ||  -> .\nFormulae used in the proof : rightunit zero_plus\n\n--------------------------SPASS-STOP------------------------------\n"
 }]
}]
```

- eprover

```json
*** Error: no matching translation or prover found
```

**Comment by eugenk** [comment]
Alright, so it's not darwin who is the bad guy, but eprover. From the top of my head, I heave no idea why this happens. 

Just to be sure (strange things are happening):
```
❯ eprover --version
E 1.8-001 Gopaldhara
```

I don't really get it because darwin and eprover should use the same default translation/comorphism/logic mapping.

What does this print?
```
curl -X POST -H "Content-Type: application/json" -d '{"format":"json"}' http://localhost:8000/provers/file%3A%2F%2F%2Fescaped%2Fpath%2Fto%2Fontohub%2Fspec%2Ffixtures%2Fontologies%2Fprove%2FSimple_Implications.casl/auto
```
I changed `prove` to `provers` and removed the prover from the request body.

**Comment by 0robustus1** [comment]
Äh.. i do not have eprover installed. Neither on OS X nor on Arch Linux is it a dependency of hets. ;)

**Comment by eugenk** [comment]
Aah, alright then

**Comment by 0robustus1** [comment]
Ok tests are green again. I shall add **eprover** as a dependency to the hets-formula (Mac OS X) and the hets-PKGBUILD (Arch Linux).
We should however take care in the future when adding new dependencies :)

**Comment by ebolloff** [comment]
```

**Comment by 0robustus1** [comment]
Yep darwin and eprover aren't dependencies of the AUR-PKGBUILD.
The only hard dependencies in the past were pellet and SPASS.

**Comment by 0robustus1** [comment]
I have now added a *darwin* PKGBUILD to the AUR. In addition to that the AUR-PKGBUILD for hets (*hets-stable*) now depends on *eprover* and *darwin*.
Additionally i've adjusted the hets-Formula (OS X) to include *eprover* as a dependency.

**Comment by ebolloff** [comment]
My tests are green now, so if you don't have the problem anymore, too, you can close this issue. But there are still some pending steps and a warning from `shoulda-matchers` in our tests.
