### ISSUE TITLE
Rugged::OSError (Failed to rename lockfile to ...: Permission denied)

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1590]
I tried to edit http://ontohub.org/dol-examples/engine.dol and then clicked "Discard".
```
Rugged::OSError (Failed to rename lockfile to '/data/git/repositories/82/objects/41/9a9ce525eb523d04d24d4f5333dec378a70f95': Permission denied):
  lib/git_repository/commit.rb:36:in `write_tree'
  lib/git_repository/commit.rb:36:in `commit_file'
  lib/git_repository/commit.rb:13:in `add_file'
  app/models/repository/git.rb:47:in `save_file'
  app/fake_records/repository_file.rb:62:in `save!'
  app/fake_records/fake_record.rb:27:in `create!'
  app/fake_records/fake_record.rb:16:in `create'
  app/controllers/files_controller.rb:50:in `update'

```

**Comment by eugenk** [comment]
Running ontohub processes as specificly users is a precondition.

**Comment by eugenk** [comment]
And #1646 should be a preconditions (please check this again)
