### ISSUE TITLE
uploading a file causes error

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1788]
when uploading a file in the file browser, I get
```
 Rugged::OSError in FilesController#create

Failed to rename lockfile to '/data/git/repositories/220/objects/1b/af1df963b85cfa74c10c568b2018c69f7a3818': Permission denied

Rails.root: /local/home/ontohub/webapp
Application Trace | Framework Trace | Full Trace

lib/git_repository/committing.rb:36:in `write_tree'
lib/git_repository/committing.rb:36:in `commit_file'
lib/git_repository/committing.rb:13:in `add_file'
app/models/repository/git.rb:47:in `save_file'
app/fake_records/repository_file.rb:62:in `save!'
app/fake_records/fake_record.rb:27:in `create!'
app/fake_records/fake_record.rb:16:in `create'
app/controllers/files_controller.rb:36:in `create'

Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"gBv/kAlNzSZf/HZUI9AR8Y0H20qgBygKYoHrlPufSdU=",
 "repository_file"=>{"file_upload_type"=>"local",
 "temp_file"=>#<ActionDispatch::Http::UploadedFile:0x007f11523cfdb0 @original_filename="Family_structured.dol",
 @content_type="application/octet-stream",
 @headers="Content-Disposition: form-data; name=\"repository_file[temp_file]\"; filename=\"Family_structured.dol\"\r\nContent-Type: application/octet-stream\r\n",
 @tempfile=#<Tempfile:/tmp/RackMultipart20160813-869-skhgqy>>,
 "remote_file_iri"=>"",
 "target_directory"=>"OWL",
 "target_filename"=>"",
 "message"=>"test of %implied in OWL"},
 "commit"=>"Upload File",
 "repository_id"=>"esslli-2016"}
```

**Comment by tillmo** [comment]
The above has happened on develop.ontohub.org, but I get a similar error on ontohub.org:
```
Rugged::OSError (Failed to rename lockfile to '/data/git/repositories/216/objects/44/4353e4dd741326503004a226acfccb9c072b33': Permission denied):
  lib/git_repository/committing.rb:36:in `write_tree'
  lib/git_repository/committing.rb:36:in `commit_file'
  lib/git_repository/committing.rb:13:in `add_file'
  app/models/repository/git.rb:47:in `save_file'
  app/fake_records/repository_file.rb:62:in `save!'
  app/fake_records/fake_record.rb:27:in `create!'
  app/fake_records/fake_record.rb:16:in `create'
  app/controllers/files_controller.rb:50:in `update'
```

**Comment by tillmo** [comment]
This only happens in specifc repositories and if the filename is `Family_structured.dol`.

**Comment by tillmo** [comment]
probably caused by #1646
