### ISSUE TITLE
cannot display mappings

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1799]
When I click on the "Mappings" tab, I get a 500:

```
ActionView::Template::Error (undefined method `gsub' for nil:NilClass):
    1: %tr.center-row
    2:   %td= mapping.kind
    3:   %td.col-md-1.right= link_to "#{mapping}:", url_for(mapping), class: 'iri', :'data-toggle' => 'tooltip', :'data-original-title' => url_for(mapping)
    4:   %td.col-md-2.right= fancy_link mapping.source
    5:   %td.col-md-1
    6:     %span.bold{:class => "#{mapping.display_connection}"}
  lib/extend/action_dispatch/routing/polymorphic_routes.rb:44:in `build_locid_url'
  lib/extend/action_dispatch/routing/polymorphic_routes.rb:12:in `block in <module:PolymorphicRoutes>'
  app/views/mappings/_mapping.html.haml:3:in `_app_views_mappings__mapping_html_haml__149852598605817394_69978974770120'
  app/views/mappings/index.html.haml:57:in `block in _app_views_mappings_index_html_haml___2764002128161480874_69978998072000'
  app/helpers/pagination_helper.rb:10:in `pagination'
  app/views/mappings/index.html.haml:13:in `_app_views_mappings_index_html_haml___2764002128161480874_69978998072000'
```

**Comment by eugenk** [comment]
Which URL did you visit?

**Comment by tillmo** [comment]
https://ontohub.org/mappings

**Comment by eugenk** [comment]
This is because the mappings with the ids

```
[2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 18, 19, 22, 23, 24, 25, 26, 27, 28, 29, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 98, 109, 112, 643, 673, 674, 675, 676, 678, 680, 681, 683, 684, 686, 687, 708, 709, 711, 712, 713, 714, 715, 716, 720, 725, 726, 731, 732, 744, 745, 746, 747, 748, 751, 752, 787, 788, 929, 939, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 973, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 994, 995, 996, 997, 998, 999, 1000, 1004, 1005, 1007, 1008, 1009, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1025, 1026, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1075, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1094, 1095, 1096, 1097, 1099, 1102, 1104, 1107, 1108, 1110, 1113, 1114, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1129, 1130, 1133, 1134, 1135, 1139, 1140, 1145, 1146, 1147, 1149, 1150, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1194, 1195, 1197, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1208, 1209, 1210, 1213, 1214, 1217, 1218, 1219, 1220, 1222, 1228, 1229, 1230, 1232, 1233, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1253, 1254, 1256, 1257, 1258, 1260, 1261, 1264, 1265, 1266, 1267, 1269, 1272, 1277, 1278, 1279, 1280, 1281, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1308, 1311, 1314, 1318, 1319, 1320, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1349, 1352, 1354, 1357, 1359, 1362, 1364, 1367, 1369, 1372, 1374, 1377, 1379, 1382, 1384, 1387, 1388, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1412, 1413, 1414, 1415, 1417, 1418, 1419, 1420, 1421, 1424, 1425, 1426, 1428, 1431, 1433, 1434, 1435, 1436, 1439, 1440, 1441, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1769, 1770, 1771, 1773, 1774, 1775, 1776, 1777, 1778, 1781, 1782, 1783, 1784, 1785, 1786, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1820, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1854, 1855, 1856, 1858, 1859, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1871, 1872, 1873, 1874, 1876, 1878, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1987, 1988, 1990, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2010, 2011, 2013, 2018, 2019, 2020, 2021, 2027, 2028, 2029, 2030, 2035, 2036, 2037, 2038, 2039, 2042, 2043, 2045, 2046, 2047, 2050, 2051, 2054, 2055, 2060, 2061, 2062, 2063, 2064, 2067, 2068, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2084, 2085]
```

had no Loc/id in the database. The newest of these mappings is from June 2015. The data migration that creates the Loc/Ids seems to have failed. I just created the Loc/Ids in the rails console and it should work now.

**Comment by tillmo** [comment]
good, works!
